### ISSUE TITLE
initial joint of the robot

### ISSUE THREAD

**Issue by Nash-dc** [Multiverse-Framework/Multiverse#16]
Hi Mr.Giang,
I follow the tutorial to build my own franka robot,but there is a problem when I try to initiate the pose of the panda
[Screencast from 18.09.2023 18:57:22.webm](https://github.com/Multiverse-Framework/Multiverse/assets/82002084/ede5df99-105a-4655-8eff-6292dab0cb22)
you can see that the robot is first initialized with the joint_inits, but soon the pose is changed and the arm keep shaking.I haven't had this problem running you pick_and_place demo before. I think I might have the problem with the yaml file
the following is my joint_inits
```
mujoco:
  joint_inits:
    panda_2_joint1: 0
    panda_2_joint2: -0.785398163397
    panda_2_joint3: 0
    panda_2_joint4: -2.35619449019
    panda_2_joint5: 0
    panda_2_joint6: 1.57079632679
    panda_2_joint7: 0.785398163397

  root_frame_id: map

multiverse:  
  length_unit: m
  angle_unit: rad
  force_unit: N
  time_unit: s
  handedness: rhs
  root_frame_id: map

  send:
    joint: [joint_rvalue, joint_tvalue]
  receive:
    StaticMeshActor_3: [position, quaternion]
```
Here is my launch file:
```
<launch>
    <arg name="namespace" default="dual_panda" />

    <group ns="$(arg namespace)">
        <include file="$(find mujoco_sim)/launch/mujoco_sim.launch">
            <arg name="config" value="$(find franka_mujoco)/config/dual_panda.yaml" />
            <arg name="world" value="$(find mujoco_sim)/model/world/empty.xml" />
            <arg name="robot" value="$(find franka_description)/robots/dual_panda_arm.urdf" />
            <arg name="use_urdf" value="true" />
            <arg name="socket_port" value="7500" />
        </include>
    </group>

    <group ns="$(arg namespace)">
        <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" />

        <rosparam command="load" file="$(find franka_control)/config/dual_panda_arm_controllers.yaml" />
	    <node name="controller_manager" pkg="controller_manager" type="controller_manager" respawn="false" output="screen" args="spawn 
		joint_state_controller 
		panda_2_joint_trajectory_controller 
		panda_2_gripper_controller" /> 
        <node name="rqt_joint_trajectory_controller" pkg="rqt_joint_trajectory_controller" type="rqt_joint_trajectory_controller" />
    </group>


    <include file="$(find giskardpy)/launch/giskardpy_dual_panda.launch" />
    <group ns="$(arg namespace)">
        <node pkg="franka_control" type="test_mimic_panda_1.py" name="test_1"
            output="screen" launch-prefix="bash -c 'sleep 5; $0 $@' " />

    </group>


</launch>
```
Here is my dual_panda_arm_controllers.yaml
```
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

panda_2_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_2_joint1
    - panda_2_joint2
    - panda_2_joint3
    - panda_2_joint4
    - panda_2_joint5
    - panda_2_joint6
    - panda_2_joint7
  gains:
    panda_2_joint1: {p: 2000, i: 100, d: 50}
    panda_2_joint2: {p: 2000, i: 100, d: 50}
    panda_2_joint3: {p: 2000, i: 100, d: 50}
    panda_2_joint4: {p: 2000, i: 100, d: 50}
    panda_2_joint5: {p: 2000, i: 100, d: 50}
    panda_2_joint6: {p: 2000, i: 100, d: 50}
    panda_2_joint7: {p: 2000, i: 100, d: 50}
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 1.0
    panda_2_joint1: { goal: 0.05 }
    panda_2_joint2: { goal: 0.05 }
    panda_2_joint3: { goal: 0.05 }
    panda_2_joint4: { goal: 0.05 }
    panda_2_joint5: { goal: 0.05 }
    panda_2_joint6: { goal: 0.05 }
    panda_2_joint7: { goal: 0.05 }

panda_1_gripper_controller:
  type: effort_controllers/GripperActionController
  joint: panda_1_finger_joint1
  gains:
    panda_1_finger_joint1: { p: 20000, i: 100, d: 50 }

panda_2_gripper_controller:
  type: effort_controllers/GripperActionController
  joint: panda_2_finger_joint1
  gains:
    panda_2_finger_joint1: { p: 20000, i: 100, d: 50 }
```
what's more, I connected this panda with the real panda in the lab.When I try to update the joint states using giskardpy by subscribing the specific topic,I keep get one error:
`/dual_panda/panda_2_joint_trajectory_controller/follow_joint_trajectory' failed to execute goal. Error: 'GOAL_TOLERANCE_VIOLATED'`
I am not very familar with writing yaml file, so I just copy all my yaml files.
It would be great if you can give me some guidances on this issue.Building the robot on MuJoCo is not trivial at all:(
I know I already asked too many questions. I am sorry that I bother you so much. I deeply appreciate your patience on my stupid question.
